/** Vue 与 React 公共组件必须共同满足的最低行为契约。 */
export const componentBehaviorMatrix = {
  VustIcon: ["render", "accessible-name"],
  VustButton: ["state", "click"],
  VustInput: [
    "value",
    "change",
    "invalid",
    "form-identity",
    "accessible-name",
    "controlled",
  ],
  VustSwitch: ["state", "keyboard", "controlled"],
  VustTag: ["render", "variant"],
  VustCard: ["render", "slots"],
  VustCheckbox: [
    "state",
    "change",
    "indeterminate",
    "form-identity",
    "accessible-name",
    "controlled",
  ],
  VustEmpty: ["render", "custom-content"],
  VustAlert: ["state", "close", "live-region"],
  VustLoading: ["state", "busy"],
  VustBreadcrumb: ["render", "navigation"],
  VustBreadcrumbItem: ["render", "current-item"],
  VustToast: ["state", "close", "live-region"],
  VustTooltip: ["state", "position", "disabled"],
  VustDescriptions: ["render", "layout"],
  VustFormItem: ["label", "hint", "error", "associations"],
  VustTabs: ["state", "change", "keyboard", "tab-semantics", "controlled"],
  VustMenu: [
    "state",
    "change",
    "keyboard",
    "navigation-semantics",
    "controlled",
  ],
  VustActionMenu: ["state", "keyboard", "menu-semantics"],
  VustDialog: ["state", "escape", "focus", "scroll-lock"],
  VustDrawer: ["state", "escape", "focus", "scroll-lock"],
  VustModal: ["state", "escape", "focus", "scroll-lock"],
  VustPagination: ["state", "change", "navigation-semantics"],
  VustSelect: [
    "state",
    "keyboard",
    "listbox-semantics",
    "position",
    "form-identity",
    "accessible-name",
    "form-value",
    "controlled",
  ],
  VustTable: [
    "render",
    "row-key",
    "fixed-columns",
    "selection",
    "select-page",
    "indeterminate",
  ],
  VustSelectionBar: ["count", "clear", "actions", "live-region"],
  VustDateTimeRangePicker: ["state", "change", "position", "controlled"],
} as const;

export type PublicComponentName = keyof typeof componentBehaviorMatrix;
